# Deluge daemon service
{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.services.deluge;
  isDeluge1 = versionOlder cfg.package.version "2.0.0";

  configDir = "${cfg.dataDir}/.config/deluge";
  configFile = pkgs.writeText "core.conf" (builtins.toJSON cfg.config);
  declarativeLockFile = "${configDir}/.declarative";

  preStart =
    if cfg.declarative then
      ''
        if [ -e ${declarativeLockFile} ]; then
          # Was declarative before, no need to back up anything
          ${if isDeluge1 then "ln -sf" else "cp"} ${configFile} ${configDir}/core.conf
          ln -sf ${cfg.authFile} ${configDir}/auth
        else
          # Declarative for the first time, backup stateful files
          ${if isDeluge1 then "ln -s" else "cp"} -b --suffix=.stateful ${configFile} ${configDir}/core.conf
          ln -sb --suffix=.stateful ${cfg.authFile} ${configDir}/auth
          echo "Autogenerated file that signifies that this server configuration is managed declaratively by NixOS" \
            > ${declarativeLockFile}
        fi
      ''
    else
      ''
        if [ -e ${declarativeLockFile} ]; then
          rm ${declarativeLockFile}
        fi
      '';
in
{
  config = mkIf cfg.enable {
    systemd.services.deluged = mkMerge [
      # Base configuration
      {
        after = [ "network.target" ];
        description = "Deluge BitTorrent Daemon";
        wantedBy = [ "multi-user.target" ];
        path = [ cfg.package ] ++ cfg.extraPackages;
        
        serviceConfig = {
          ExecStart = ''
            ${cfg.package}/bin/deluged \
              --do-not-daemonize \
              --config ${configDir}
          '';
          # To prevent "Quit & shutdown daemon" from working; we want systemd to
          # manage it!
          Restart = "on-success";
          User = cfg.user;
          Group = cfg.group;
          UMask = "0002";
          LimitNOFILE = cfg.openFilesLimit;
        };
        
        preStart = preStart;
      }
      
      # VPN namespace binding if enabled
      (mkIf cfg.vpn.enable {
        bindsTo = [ "netns@${cfg.vpn.namespace}.service" ];
        requires = [ "network-online.target" "wg.service" ];
        after = [ "wg.service" ];
        serviceConfig.NetworkNamespacePath = "/var/run/netns/${cfg.vpn.namespace}";
      })
    ];
  };
}
